#######################################################################################
# Book settings
title : Juan
author: Juan Huerta
logo: '0.png'

# Information about where the book exists on the web
description: >-
  A personal website with data science resources

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/executablebooks/jupyter-book  #if this stops working i cloned the repo personal_projects
  path_to_book                : "mini-book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
